# Generated by Django 2.2.4 on 2019-11-11 15:26

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barg_three', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bid',
            field=otree.db.models.FloatField(default=30.0, null=True),
        ),
    ]
