# Generated by Django 2.2.4 on 2019-11-11 15:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barg_three', '0002_auto_20191111_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bid',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
