# Generated by Django 2.2.4 on 2019-11-11 15:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barg_three', '0003_auto_20191111_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bid_role',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
